version: '3.8'

services:
  frontend:
    image: superlike1/frontend-app:latest
    ports:
      - "3001:3000"
    depends_on:
      - backend

  backend:
    image: superlike1/backend-app:latest
    ports:
      - "5000:5000"

  gerador:
    image: superlike1/gerador-app:latest
    volumes:
      - ./backend:/app
    depends_on:
      - backend

  flaskapi:
    image: superlike1/flask-app:latest
    ports:
      - "5051:5050"
    depends_on:
      - db
  db:
    image: superlike1/mysql-app:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: walker1207
      MYSQL_DATABASE: faculdades1
      MYSQL_USER: dbpi
      MYSQL_PASSWORD: walker1207
    volumes:
      - db_data:/var/lib/mysql

  rscript:
    image: superlike1/rscript-app:latest
    depends_on:
      - gerador

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3011:3011"
    depends_on:
      - db
      - loki
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  loki:
    image: grafana/loki:2.8.2
    ports:
      - "9091:9091"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/var/lib/loki

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9010:9010" # Porta padrão do Prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro # Monta como arquivo somente leitura
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

volumes:
  db_data:
  grafana_data:
  loki_data: