version: '3.8'

services:
  frontend:
    image: superlike1/frontend-app:latest
    ports:
      - "3001:3000"
    depends_on:
      - backend

  backend:
    image: superlike1/backend-app:latest
    ports:
      - "5000:5000"

  gerador:
    image: superlike1/gerador-app:latest
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: python gerador.py

  flaskapi:
    image: superlike1/flask-app:latest
    ports:
      - "5051:5050"
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: walker1207
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - ./my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  rscript:
    image: superlike1/rscript-app:latest
    depends_on:
      - db
    command: Rscript limpeza.r

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
      - loki
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  loki:
    image: grafana/loki:2.8.2
    ports:
      - "9091:9091"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/var/lib/loki

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9010:9010"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  spark-master:
    build:
      context: ./spark
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - PYSPARK_PYTHON=python3
    ports:
      - "7077:7077"
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./spark:/opt/spark/scripts
    networks:
      - default


  spark-worker:
    build:
      context: ./spark
      dockerfile: Dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - PYSPARK_PYTHON=python3
    ports:
      - "8081:8081"
    depends_on:
      - spark-master
    networks:
      - default

volumes:
  db_data:
  grafana_data:
  loki_data:

networks:
  default:
    name: jenkins-pi-network
