version: "3.8"

services:
  frontend:
    image: superlike1/frontend-app:latest
    ports:
      - "3003:3000"
    depends_on:
      - backend
    networks:
      - app_net

  backend:
    image: superlike1/backend-app:latest
    ports:
      - "5000:5000"
    networks:
      - app_net

  gerador:
    image: superlike1/gerador-app:latest
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    command: python gerador.py
    networks:
      - app_net

  flaskapi:
    image: superlike1/flask-app:latest
    ports:
      - "5051:5050"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_net
    volumes:
      - ./home/olivia-linux/Documentos/jenkins-pi/api/pi-do-mal.json:/app/pi-do-mal.json
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: walker1207
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - ./my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_net

  rscript:
    image: superlike1/rscript-app:latest
    depends_on:
      db:
        condition: service_healthy
    command: Rscript limpeza.r
    networks:
      - app_net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3002:3000"
    depends_on:
      - db
      - loki
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app_net

  loki:
    image: grafana/loki:2.8.2
    ports:
      - "9052:9091"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/var/lib/loki
    networks:
      - app_net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9030:9030"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - app_net


volumes:
  db_data:
  grafana_data:
  loki_data:

networks:
  app_net:
    driver: bridge
