services:
  frontend:
    image: superlike1/frontend-app:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: ["serve", "-s", "public", "-l", "3000"]

  backend:
    image: superlike1/backend-app:latest
    ports:
      - "5000:5000"

  gerador:
    image: superlike1/gerador-app:latest
    command: ["python", "gerador.py"]

  db:
    image: superlike1/mysql-app:latest
    ports:
      - "3307:3306"
    depends_on:
      - gerador
    environment:
      MYSQL_ROOT_PASSWORD: walker1207
      MYSQL_DATABASE: app_db
      MYSQL_USER: dbpi
      MYSQL_PASSWORD: walker1207
    volumes:
      - db_data:/var/lib/mysql

  rscript:
    image: superlike1/rscript-app:latest
    depends_on:
      - gerador

volumes:
  db_data:
