global:
  scrape_interval: 15s # Intervalo padrão para coleta de métricas

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3011']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:9091']